### PR TITLE
Use unique names for queue unique cache configurations

### LINKED ISSUE #113: QueueManager Fails when Multiple Queue Configs Contain uniqueCache Key
When multiple queue configs have the `uniqueCache` key QueueManager fails to load with the following error:
> BadMethodCallException: Cannot reconfigure existing key "Cake/Queue.queueUnique"
>
> /code/vendor/cakephp/cakephp/src/Core/StaticConfigTrait.php:91
> /code/src/QueueManager.php:130

The following test can be used to trigger the error:
```php
public function testMultipleUniqueCache()
{
    QueueManager::setConfig('test', [
        'url' => 'null:',
        'uniqueCache' => [
            'engine' => 'File',
        ],
    ]);
    QueueManager::setConfig('test2', [
        'url' => 'null:',
        'uniqueCache' => [
            'engine' => 'File',
        ],
    ]);
}
```

### PR DESCRIPTION
**Pull request by sheldonreiff**
Prevents an exception when multiple configs are set with `uniqueCache` configured.

Fixes #113

### CODE REVIEW

File: src/QueueManager.php [hunk 1]
```diff
@@ -127,7 +129,9 @@ public static function setConfig($key, $config = null): void
 
             $cacheConfig = array_merge($cacheDefaults, $config['uniqueCache']);
 
-            Cache::setConfig('Cake/Queue.queueUnique', $cacheConfig);
+            $config['uniqueCacheKey'] = "Cake/Queue.queueUnique.{$key}";
```
Comment (markstory) [inline src/QueueManager.php:132]: Couldn't this be put into the `defaults` so that userland code can define it if they really need to?

```php
$cacheDefaults` = [
  'duration' => '+24 hours',
  'uniqueCacheKey' => "Cake/Queue.queueUnique.{$key}"
];
```

Comment (sheldonreiff) [reply src/QueueManager.php:132]: The whole array nested under `uniqueCache` is passed directly through to `Cache::setConfig()`, so maybe that would be slightly confusing that `uniqueCacheKey` isn't part of the cache config? We could bump it up a level though and let it be configurable as part of the main config. So configuring the unique cache would look like this:
```
'uniqueCacheKey' => 'someCustomKey', // (optional)
'uniqueCache' => [
    'engine' => 'File',
],
```

Comment (markstory) [reply src/QueueManager.php:132]: > maybe that would be slightly confusing that uniqueCacheKey isn't part of the cache config? 

Yeah that would be odd. Lets roll with what you have so far. If we come up with use-cases that require custom cache key configuration control we can revisit then.
